FROM node:latest

WORKDIR /usr/src/app

RUN apt-get update && \
  apt-get install -y --no-install-recommends dumb-init netcat-traditional && \
  wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
  chmod +x /usr/bin/wait-for
